### PR TITLE
fix(react): date compare in shallow equal function

### LINKED ISSUE #160: Date store not synced properly when using a selector
### Describe the bug

given this store:
```ts
import { Store } from '@tanstack/react-store';

export const RootState = new Store({
    selectedDay: new Date(),
});
```
`a` is refreshed but `b` is not
```ts
export function DatePicker() {
  const a = useStore(RootState);
  const b = useStore(RootState, (s) => s.selectedDay);
  // ...
}
```

---

@thazlett16 said on discord:

> I'm guessing this has to do with the shallow compare:
> https://github.com/TanStack/store/blob/main/packages/react-store/src/index.ts#L34
> 
> I know in Redux they generally recommend storing dates in a serializeable format like the string form (RFC 3339, ISO 8601 etc)

### Steps to Reproduce the Bug or Issue

example here: https://stackblitz.com/edit/tanstack-store-thn7c7az?file=src%2Findex.tsx

### Expected behavior

both `a` and `b` should refresh (unless dates are not supposed to be supported)

### PR DESCRIPTION
**Pull request by SashaZel**
Fix #160

### CODE REVIEW

**Comment by crutchcorn** [comment]
Nice! This is a great fix. Can we apply the same fix to the other frameworks with similar `shallow` methods?

**Comment by SashaZel** [comment]
> Nice! This is a great fix. Can we apply the same fix to the other frameworks with similar `shallow` methods?

Hi,
Done.

**Comment by jay-babu** [comment]
@crutchcorn any chance this can be merged?

File: packages/react-store/src/index.ts [hunk 1]
```diff
@@ -61,6 +61,11 @@ export function shallow<T>(objA: T, objB: T) {
     return true
   }
 
+  if (objA instanceof Date && objB instanceof Date) {
+    if (objA.getTime() !== objB.getTime()) return false
+    return true
```
Comment (mainendra) [inline packages/react-store/src/index.ts:66]: nit: how about just `return objA.getTime() === objB.getTime()`?

**Comment by danielepintore** [comment]
Hello, any updates on this?
